name: Playwright Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Instalar navegadores Playwright
        run: npx playwright install --with-deps

      - name: Rodar testes (Chromium)
        run: npx playwright test --project=chromium

      - name: Publicar relatório HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/

        with:
          name: playwright-report-${{ matrix.browser }}
          path: playwright-report/
